benchmark-scripts/format_avc_mp4.sh, get-gpu-info.sh
=> fix: replace dmesg with the more stable lspci command

benchmark-scripts/benchmark.sh
Now if --workload is placed in front of pipeline options, it will work.  Also works if placed in-between or after the pipeline options.
Closes: #67
--workload can work in any position when running benchmark.sh script
close: #**67**
can test with either position of --workload
- sudo benchmark.sh --pipelines 1 --logdir mytest/data --duration 120 --init_duration 60 --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload dlstreamer --ocr_disabled --barcode_disabled --classification_disabled
- sudo benchmark.sh --pipelines 1  --workload dlstreamer --logdir mytest/data --duration 120 --init_duration 60 --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --ocr_disabled --barcode_disabled --classification_disabled
both cases should run as normal and works without any syntax …
=> feat: enhance the benchmark script to handle --workload option in any argument position

docker-run.sh
Closes: #75
set WORKLOAD_SCRIPT default to docker-run-dlstream.sh so it will correct the message.
close: #75 
1. go to xeon or arc supported machine using meshcentral.com
2. on automated-self-checkout directory, call command `./docker-run.sh --platform core --inputsrc rstp://127.0.0.1:8554/camera_0`
3. when not providing --workload, it should default to dlstreamer pipeline run.
=> fix: fixed docker-run.sh with wrong message when no --workload option

benchmark-scripts/benchmark.sh, configs/dlstreamer/framework-pipelines/stream_density.sh, configs/opencv-ovms/cmd_client/main.go
Fixes: #187
Add the missing PipelineInputArgs in ovms-client code when running in stream-density mode
close: #**187**
- re-build the ovms-client: `make build-ovms-client`
- change directory to **benchmark_scripts** folder
- if you have not built the benchmark docker images, do the command `make` to build all benchmark related docker images.
- run stream density with grpc_python pipeline profile: `PIPELINE_PROFILE="grpc_python" sudo -E ./benchmark.sh --stream_density 14.9 --logdir mytest/data --duration 120 --init_duration 20 --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload opencv-ovms`
- once it is done, check the stream_density log in ../results/ folder, you should see the max number of pipelines to support the target FPS in the log: `cat …
=> fix: Resolve the issue of OVMS stream density mode for grpc_python pipeline profile

configs/opencv-ovms/grpc_go/Dockerfile, configs/opencv-ovms/grpc_go/entrypoint.sh, configs/opencv-ovms/grpc_go/main.go, configs/opencv-ovms/scripts/run_grpc_go.sh
grpc-go pipeline's output result is changing from latency.txt to pipeline#.log and r#.jsonl to align with python's output result
- run camera simulator
- make build-grpc-go
- make build-ovms-client
- run this script: PIPELINE_PROFILE="grpc_go" sudo -E ./docker-run.sh --workload opencv-ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0
- you should see the result logs inside results/ directory
To test Debug mode:
- add `-e DEBUG="1" \` after `-e PIPELINE_PROFILE="$PIPELINE_PROFILE" \` in docker-run-opencv-ovms.sh
- make build-grpc-go
-  run this script: PIPELINE_PROFILE="grpc_go" sudo -E ./docker-run.sh --workload opencv-ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0
- you should not see any result logs inside results/ directory, …
=> feat: output FPS for go pipeline

configs/opencv-ovms/grpc_go/entrypoint.sh, configs/opencv-ovms/scripts/run_grpc_go.sh
Fixes: #191
- build grpc-go: `make build-grpc-go`
- change directory to benchmark-scripts: `cd benchmark-scripts`
- run grpc_go pipeline profile with 2 pipelines: `PIPELINE_PROFILE="grpc_go" sudo -E ./benchmark.sh --pipelines 2 --logdir mytest/data --duration 100 --init_duration 30 --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload opencv-ovms`
-
=> fix: resolve the issue of running multiple instances of grpc-go pipelines

configs/dlstreamer/framework-pipelines/stream_density.sh, configs/opencv-ovms/grpc_go/main.go, configs/opencv-ovms/grpc_go/pkg/ovms/inferRequest.go
fix some fatal log that quits the grpc-go pipeline. and add retry logic for handling sending request to the model server
- rebuild the grpc-go: `make build-grpc-go`
- run the stream density from benchmark-scripts directory: `PIPELINE_PROFILE="grpc_go" sudo -E ./benchmark.sh --stream_density 15.0 1 --logdir mytest/data --duration 120 --init_duration 30 --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload opencv-ovms`
-
=> feat: better error handling for grpc-go while running stream density

configs/opencv-ovms/cmd_client/main.go, configs/opencv-ovms/cmd_client/res/grpc_go/configuration.yaml, configs/opencv-ovms/grpc_go/Dockerfile, configs/opencv-ovms/grpc_go/entrypoint.sh, configs/opencv-ovms/grpc_go/main.go, configs/opencv-ovms/grpc_go/stream_density_run.sh, configs/opencv-ovms/scripts/run_grpc_go.sh, docker-run-opencv-ovms.sh
Add the stream density run in configuration yaml file so that it can be dynamically launched inside the grpc go docker container.
No multiple docker containers running no more.  It is multiple instances of pipeline executable in stream density mode.
=> refactor: stream density refactor for grpc_go profile

docker-run-opencv-ovms.sh
Fix the docker run ovms launch script to resolve this issue.
Fixes: #211
close: #**211**
- change directory to benchmark-scripts: `cd ./benchmark-scripts/`
- download the sample video from script if not yet: `./download_sample_videos.sh`
- run 11 pipelines on grpc_python profile for example: `PIPELINE_PROFILE="grpc_python" sudo -E ./benchmark.sh --workload opencv-ovms --pipelines 11 --logdir mytest/data --duration 120 --init_duration 60 --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0`
- observe that the grpc port issue is gone from console or log file
-
=> fix: resolve the GRPC port issue in the script when number of pipelines is more than 10

.github/PULL_REQUEST_TEMPLATE.md
Currently the Pull Request template markdown file has contribution guideline pointing to EdgeX md file, which should point to this project contribution md file.
=> fix: update the contribution hyperlink in pull request template markdown

benchmark-scripts/collect_platform_metrics.sh
Currently, the xpum port number is not set and empty when running in 2nd run of benchmarking, specifically for Xeon system.  This commit gives the default value of xpum port number and thus resolves the issue.
Fixes: #229
close: #**229**
=> fix: resolve the empty xpum port setting logic issue for Xeon platform

download_models/downloadModelsFromList.sh
downloaded ovms models with standard - in the name instead of _, so this PR just remove the workaround.
run with command:
PIPELINE_PROFILE="object_detection" RENDER_MODE=0 MQTT=127.0.0.1 sudo -E ./benchmark.sh --pipelines 1 --logdir mytest/data --duration 120 --init_duration 120 --platform core --inputsrc rtsp://127.0.0.1:8554/camera_3 --workload opencv-ovms
the pipeline should run with no error and good result.
=> fix: download standard model ovms name instead of name with _

Makefile
Use the current user id and group id while running make build-docs and make serve-docs.
This resolve the issue of the whole `./docs` directory owned by root after running `make build-docs`
- run `make build-docs`
- directory listing: `ls -al ./docs` to notice that the directory ownership should now be your user id and group id **instead of root:root**
=> fix: update make-build-docs to use the current user id and group id instead of root user

Makefile, telegraf/Dockerfile
- Add the local makefile target for hadolint on checking error level on Dockerfile locally for developers
- Fix the error level issue from hadolint report
-  run `make hadolint` to see if any error issue on Dockerfiles or not
=> feat: add hadolint Docker makefile target for developers used locally

configs/opencv-ovms/cmd_client/main.go, configs/opencv-ovms/cmd_client/ovmsClientConf_test.go, configs/opencv-ovms/cmd_client/ovmsGrpcPort.go, configs/opencv-ovms/cmd_client/portfinder/findPort.go, configs/opencv-ovms/cmd_client/portfinder/findPort_test.go, configs/opencv-ovms/scripts/get_server_grpc_port.sh, run-ovms.sh, run_smoke_test.sh
- Make the cid_count value setting more robust when the client side containers crashed by other containers.
- Make getting GRPC_PORT number more robust by free opened port from system
- Add profile-launcher log output into file as we can track its running contents for easier debugging information
- Update run-ovms.sh and run-smoke-test.sh to remove cid_count and GRPC_PORT check as it is taken care by profile-launcher now
Closes: #328
close: #**328**
- unit-test: `make unit-test-profile-launcher`  should all PASSED
- build profile-launcher: `make build-profile-launcher` 
- run camera-simulator: `make run-camera-simulator`
- functional test: you can launch multiple instance profiles to see the behavior
```console
1. PIPELINE_PROFILE="object_detection" RENDER_MODE=1 sudo …
```
=> feat: refactor the way for the value of cid_count env and GRPC_PORT env

.github/workflows/integration.yaml, Makefile, benchmark-scripts/download_sample_videos.sh, benchmark-scripts/format_avc_mp4.sh, docs_src/OVMS/pipelinesetup.md, download_models/downloadOVMSModels.sh, get-realsense-serialno.sh, run_smoke_test.sh
=> feat: add integration test github workflow action

benchmark-scripts/consolidate_multiple_run_of_metrics.py
close: #256
on serpent canyon, execute:
1. cd benchmark-scripts && PIPELINE_PROFILE="object_detection" DEVICE=GPU RENDER_MODE=0 sudo -E ./benchmark.sh --pipelines 5 --logdir testRun/5stream/run0 --duration 120 --init_duration 60 --platform dgpu.1 --inputsrc rtsp://127.0.0.1:8554/camera_0
2. make consolidate ROOT_DIRECTORY=testRun/5stream
Observe the values for GPU.0 on the summary.cvs file
=> fix: Updating GPU utilization field for DGPU

Makefile, src/docker-compose.yml
Add new run-headless command for a one command without the render mode.
=> feat: Add headless version of run-demo

helm/Makefile, helm/docker-compose.yml, helm/swarm.md
* Adding docker swarm support
* Best practice is to not mount paths in the docker compose, since all nodes require to have the same path.
=> Adding docker swarm support

src/pipeline-server/grafana/dashboard.json
Remove unused graph from visualizer
make run-pipeline-server
=> fix: Remove average fps graph from UI

README.md, benchmark-commands.md
=> docs: markdown improvements
