intel-retail/automated-self-checkout

benchmark-scripts/consolidate_multiple_run_of_metrics.py
the consolidate python script errors out when the input pcm.csv has unmatch number of fields in some lines
added extra flag in pd.read_csv() to skip or ignore these bad csv lines so the consolidate script can continue processing
Fixes: #4
_The PR review is to check for sustainability and correctness.  Sustainability is actually more business critical as correctness is largely tested into the code over time.   Its useful to keep in mind that SW often outlives the HW it was written for and engineers move from job to job so it is critical that code developed for Intel be supportable across many years.  It is up to the submitter and reviewer to look at the code from a perspective of what if we have to debug this 3 years from now after the author is no longer available and defect databases …
=> fix: Fix pcm.csv parsing issue

benchmark-scripts/copy-platform-metrics.sh
Add the preserve flag -p to cp command while copying results from parent directory so that the timestamps of pipeline log files is preserved
Fixes: #3
_The PR review is to check for sustainability and correctness.  Sustainability is actually more business critical as correctness is largely tested into the code over time.   Its useful to keep in mind that SW often outlives the HW it was written for and engineers move from job to job so it is critical that code developed for Intel be supportable across many years.  It is up to the submitter and reviewer to look at the code from a perspective of what if we have to debug this 3 years from now after the author is no longer available and defect databases have been lost.  Yes, that happens all the time when we are working with time scales of …
=> fix: Fix the issue of copied log files timestamp

docs_src/hardwaresetup.md
=> docs: Fix docs regarding to kernel update apt-get install issue

benchmark-scripts/results_parser.py
Check the value of barcode object before increasing the barcode_count
Fixes: #11
_The PR review is to check for sustainability and correctness.  Sustainability is actually more business critical as correctness is largely tested into the code over time.   Its useful to keep in mind that SW often outlives the HW it was written for and engineers move from job to job so it is critical that code developed for Intel be supportable across many years.  It is up to the submitter and reviewer to look at the code from a perspective of what if we have to debug this 3 years from now after the author is no longer available and defect databases have been lost.  Yes, that happens all the time when we are working with time scales of more than 2 years.  When reviewing your code it is important to look at …
=> fix: resolve the issue of barcode count from parser

Dockerfile.igt, docker-run.sh, docs_src/benchmark.md, docs_src/pipelinerun.md, docs_src/pipelinesetup.md
=> Igt repo fix

docs_src/pipelinerun.md
=> doc update - fix typos

docs_src/hardwaresetup.md
=> fix: sudo required to run docker-build.sh

modelDownload.sh
=> fix models already exists, exiting... in multiple runs

docs_src/pipelinebenchmarking.md
=> fix: docker-build-igt required by benchmark.sh

get-options.sh, test_default_dgpu_ocr.sh
This resolve the issue #10
Closes: #10
Author Mandatory …
=> feat: make default --ocr 5 GPU as value when only specified platform dgpu without --ocr

docs_src/release-notes/v1-0-0.md, docs_src/releasenotes.md
This resolve the issue #16
Closes: #16
Author Mandatory …
=> docs: Update release notes for 1.0.0

docs_src/release-notes/v1-0-0.md, docs_src/releasenotes.md
=> Release notes

docs_src/mkdocs.yml, docs_src/toubleshooting.md
=> Docs: remove troubleshooting and use FAQ instead

.gitignore, docs_src/pipelinebenchmarking.md, docs_src/pipelinesetup.md
=> docs: update pipeline setup documentation from UX feedback

docs_src/platforms.md
=> docs: Update platforms to i5 or i7

docs_src/pipelinerun.md
=> docs: Pipelinerun update

README.md, docs_src/index.md, docs_src/mkdocs.yml
=> Docs: update index.md based on UX feedback

benchmark-scripts/format_avc_mp4.sh, benchmark-scripts/test_format_avc_mp4.sh
=> fix: fixed download_sample_videos.sh should support non dgpu systems

benchmark-scripts/Dockerfile.benchmark
=> fix: Add missing lspci utility inside benchmark Docker image

Makefile, camera-simulator/camera-simulator.sh
=> feat: added Makefile for pipeline run

Makefile, docs_src/pipelinerun.md, docs_src/pipelinesetup.md
=> docs: Updated for Makefile added

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
=> Enh: simplify PR template and add issues template

benchmark-scripts/benchmark.sh, benchmark-scripts/test_stream_density.sh, configs/dlstreamer/framework-pipelines/stream_density.sh, docker-run-dlstreamer.sh, get-options.sh
Now the increment of pipeline numbers can be larger if the system is high power and performed well:
The increment number is **dynamically adjusted** based the actual average FPS per stream and the target FPS.
The searching policy is greedy to attempt to get to the maximum pipelines first and then decrement by 1 at a time
to find the maximum number of pipelines reaching the target FPS.
Closes: #51
_The PR review is to check for sustainability and correctness.  Sustainability is actually more business critical as correctness is largely tested into the code over time.   Its useful to keep in mind that SW often outlives the HW it was written for and engineers move from job to job so it is critical that code developed for Intel be supportable across many years.  It is up to the submitter and …
=> feat: enhance stream density function

.github/dependabot.yml, .github/workflows/banditscan.yaml, .github/workflows/codeql.yaml, .github/workflows/goscans.yaml, .github/workflows/hadolintscan.yaml, .github/workflows/pythonCodeStyleScan.yaml, .github/workflows/reviewdog.yaml, .github/workflows/shellcheck.yaml, .github/workflows/trivy-scan.yaml, .rdjson.jq, .reviewdog.yml, .trivyConf.yaml, benchmark-scripts/consolidate_multiple_run_of_metrics.py
=> feat: Add github actions

.github/workflows/reviewdog.yaml, .github/workflows/shellcheck.yaml, .reviewdog.yml
=> fix: Update shecllcheck minimum severity to warning

.github/workflows/reviewdog.yaml
=> fix: Remove actoins/checkout from reviewdog

benchmark-scripts/smoke_test.sh
Adding automated smoke test for core use cases
build soc-sco image
build benchmark images
sh smoke_test.sh
=> feat: adding core smoke test

benchmark-scripts/collect_platform_metrics.sh
Updating collect_platform_metrics.sh to run xpu manager on all found GPU devices instead of only running on GPU 0
close: #77
=> Fix: update collect platform metrics to handle multiple gpu devices

docs_src/camera_serial_number.md, docs_src/faq.md, docs_src/hardwaresetup.md, docs_src/index.md, docs_src/pipelinebenchmarking.md, docs_src/pipelinerun.md, docs_src/pipelinesetup.md, docs_src/platforms.md, docs_src/query_usb_camera.md, docs_src/references.md, docs_src/release-notes/v1-0-0.md, docs_src/roadmap.md
updates for release 1.0.1
close: #88
=> Docs: updates for release 1.0.1

benchmark-scripts/format_avc_mp4.sh
: invert the format avc mp4 script tag logic to match our expected tag
close: #91
1. build only the sco-soc:2.0 image on your system
2. cd to benchmark-scripts
3. run ./download_sample_videos.sh 1080 1920 15
4. verify that coca-cola-4465029-1080-15-bench.mp4 exists in /sample-media
=> Fix: invert the format avc mp4 script tag logic to match our expected tag

.github/workflows/codescan.yaml
=> feat: add trivy code scan

benchmark-scripts/Dockerfile.benchmark, benchmark-scripts/collect_platform_metrics.sh, benchmark-scripts/get-gpu-info.sh
=> Fix: pcm directory inconsistent between dockerfile and run script

Makefile, clean-containers.sh
closes: #100
close: #100 
make clean-ovms-client
make clean-model-server
make clean-ovms
make clean-all
=> feat: Add cleaning ovms containers to makefile

README.md, docs_src/index.md, docs_src/release-notes/v1-0-0.md
- [ x] Updated Documentation as relevant to the changes
Name change of the reference
N/A
n/a
=> name change

configs/opencv-ovms/models/2022/config.json
closes: #112
close: #112 
check automated-self-checkout/configs/opencv-ovms/models/2022/config.json, the device should be CPU
=> feat: Made CPU as default device for ovms pipeline

benchmark-scripts/collect_platform_metrics.sh
Fix: fix igt log output path in the docker run command
close: #109 
Run benchmark.sh
see igt log files in the output directory
=> Fix: fix igt log output path in the docker run command

README.md, docs_src/index.md, docs_src/release-notes/v1-0-1.md
=> Docs: revert the package name back to implementation

docs_src/pipelinesetup.md
closes: #119
updated the pipelinesetup.md L28 link to be corrected one
close: #119 
docs_src/pipelinesetup.md L28, the link should include ../configs/dlstreamer/
=> fix: fixed pipelinesetup doc has incorrect link to models.list.yml

Dockerfile.bitModel, download_models/download_mo_bit_models.sh
closes: #115
close: #115 
docker build -f Dockerfile.bitModel -t bit_model_downloader:dev .
docker run -it bit_model_downloader:dev
=> feat: Added dockerfile.bitModel to download bit models

docker-run-opencv-ovms.sh
Closes: #124
added OVMS sample image downloading process into the OVMS run script
close: #124 
1. check that automated-self-checkout/configs/opencv-ovms/images doesn't have image file after clone the REPO
2. make build-ovms-server
3. make build-ovms-client
4. run OVMS run script:  ./docker-run.sh --workload opencv-ovms --platform core --inputsrc http://127.0.0.1:8554/camera_0
5. check that automated-self-checkout/configs/opencv-ovms/images again, the `sample-bottle.jpg` was downloaded and in place
=> feat: added OVMS sample image download into run script

README.md
docs: update documentation link to github pages
=> docs: update documentation link to github pages

docs_src/OVMS/pipelinerun.md, docs_src/OVMS/pipelinesetup.md
Closes: #65
Updated doc to include gRPC (OVMS) info
close: #65 
you should see OVMS folder under docs_src directory, this OVMS folder includes OVMS pipeline setup and pipeline run documentation.
=> docs: Updated doc to include OVMS info

mkdocs.yml
closes: #131
Updated mkdoc.yml file to nav to OVMS docs
close: #131 
1. go to mkdocs.yml, you should see nav: with Opencv-ovms setup that includes all OVMS pipelinesetup.md and pipelinerun.md
=> docs: Updated mkdoc to navigate to OVMS docs

.github/workflows/build.yaml, .github/workflows/trivy-scan.yaml
Adding a parallel work flow that builds all images 
=> feat: Add docker image build to workflows

benchmark-scripts/smoke_test.sh
feat: add platform and CPU_ONLY parameters to enable smoke testing on all platform types
build base images
build benchmark images
run "./smoke_test.sh core 0
=> feat: add platform and CPU_ONLY parameters to enable smoke testing on all platform types

.github/.hadolint.yaml, .github/.reviewdogConfig.yml, Dockerfile.bitModel, Dockerfile.dgpu, Dockerfile.docs, Dockerfile.ovms-client, Dockerfile.soc
tested both images for soc and dgpu
1. run `./benchmark-scripts/smoke_test.sh` on walserv3
2. run `./benchmark-scripts/benchmark.sh --pipelines 2 --logdir mytest/data --duration 60 --init_duration 60 --platform dgpu --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload dlstreamer --ocr_disabled --barcode_disabled --classification_disabled`
test doc image
=> fix: resolve hadolint issues

.github/.reviewdogConfig.yml, .github/workflows/reviewdog.yaml
=> fix: Save scan results to artifact

Makefile
close: #**142**
just re-run `make build-ovms-server` **twice** and it should all work.
=> Fix build ovms server make command re-build issue

docs_src/pipelinesetup.md
=> docs: point model list to github model file

.github/workflows/codeql.yaml, .github/workflows/trivyimagescan.yaml
=> fix: update the github workflow from branch 1.5.0 to main branch

benchmark-scripts/benchmark.sh, docs_src/pipelinebenchmarking.md
Add performance mode parameter
close: #55
run benchmark.sh using
- '--performance_mode performance'
- '--performance_mode powersave'
- no '--performance_mode' set (should default to powersave
=> feat: Add performance mode parameter

.github/workflows/build.yaml
=> fix: change github action build to be on demand

.github/workflows/trivyimagescan.yaml
refactored trivy image scan workflow to resolve syntax error
=> fix: Resolve syntax error for trivy image scan workflow

.github/.trivyConf.yaml, .github/workflows/reports.yaml, .github/workflows/trivy-scan.yaml
added reports.yaml
updated trivy-scan.yaml to push results to github security tab
=> feat: Add workflow creates security related reports

.gitignore, configs/opencv-ovms/cmd_client/res/configuration.yaml, configs/opencv-ovms/scripts/grpc_python.py, configs/opencv-ovms/scripts/run_grpc_kserv.sh, docker-run-opencv-ovms.sh, docs_src/OVMS/pipelinesetup.md, download_models/downloadOVMSModels.sh, download_models/download_mo_bit_models.sh
- start camera simulator:  ./camera-simulator/camera-simulator.sh
- docker-run to test it:  sudo ./docker-run.sh --workload opencv-ovms --platform core --inputsrc http://127.0.0.1:8554/camera_0 
- the log file of ovms-client0 should be running without error:  `docker logs ovms-client0`
- the log file of bit-model output log should be without error: `sudo cat ./results/r0.jsonl`
=> feat: add BIT_model downloader and update the configuration to run it

README.md
=> fix: Add dataset disclaimer

README.md
=> docs: Add dataset disclaimer

Makefile, docs_src/OVMS/pipelinerun.md
close: #**183**
- run up the grpc-go profile and observed both `ovms-client0` and `dev` containers are up and running
- run make clean up: `make clean-ovms-client`  and it should clean up both ovms-client0 and dev containers.
=> Fix ovms client cleanup grpc go

download_models/downloadOVMSModels.sh
When there was only segmentation model downloaded previously, then the current model downloader will not download BIT model and/or yolov5 model.
This is due to the problematic checking only on segmentation model in ovms model downloader.  This PR fixes this issue.
Fixes: #185
Change the checking logic of the existing model not only for segmentation model but also checking other model individually.
close: #**185**
- manually delete any model from models folder: eg. `sudo rm -rf configs/opencv-ovms/models/2022/BiT_M_R50x1_10C_50e_IR/`   or `sudo rm -f config/opencv-ovms/models/2022/yolov5s/`.  Notice that this simulates the previously downloaded segmentation model only.
- change directory to ./download_models folder
- run `./downloadOVMSModels.sh`
- you should now see …
=> fix: resolve the ovms model downloader issue

configs/opencv-ovms/grpc_go/main.go
Fixes: #194
also include the pre-processing like resizing time for being fair about the total time calculation.
close: #**194**
See the detail steps in issue itself and now the number from jsonl should be `frame per second` (fps) now.
=> fix: correct the fps calculation in grpc_go

configs/opencv-ovms/cmd_client/res/grpc_python/configuration.yaml, configs/opencv-ovms/scripts/grpc_postprocess.py, configs/opencv-ovms/scripts/grpc_python.py
Adding logic to support yolov5s pipeline with the grpc_python profile.
close: #197 
1. Modify grpc_python configuration.yaml so model_name=yolov5s
2. PIPELINE_PROFILE="grpc_python" sudo -E ./docker-run.sh --workload opencv-ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0
3. See inference outputs
=> feat: Support yolov5s pipeline with grpc_python

CONTRIBUTING.md
Adding contribution guideline document.
=> feat: Add CONTRIBUTING.md

configs/dlstreamer/framework-pipelines/stream_density.sh
- build the latest grpc-go: `make build-grpc-go`
- change directory to benchmark-scripts: `cd ./benchmark-scripts`
- run stream density for grpc-go profile: `PIPELINE_PROFILE="grpc_go" sudo -E ./benchmark.sh --stream_density 15.0 --logdir mytest/data --duration 120 --init_duration 60 --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload opencv-ovms`
=> feat: enhance stream density cleanup processes logic for better handling cleanup docker process inside a script

configs/opencv-ovms/cmd_client/res/gst/configuration.yaml, configs/opencv-ovms/scripts/run_gst.sh, docker-run-opencv-ovms.sh
Adding a profile for DLStreamer pipelines
=> feat: Add DLStreamer profile

Makefile
Closes: #203
close: #203 
1. ./camera-simulator/camera-simulator.sh
2. sudo ./docker-run.sh --workload dlstreamer --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --ocr_disabled --barcode_disabled
3. you will see 3 log files generated under results/ folder
4. run `make clean-all`, this should clean all containers and results/ folder
=> feat: Add clean results folder to makefile clean-all

Makefile, benchmark-scripts/benchmark.sh, configs/opencv-ovms/models/2022/Dockerfile.updateDevice, configs/opencv-ovms/models/2022/config_template.json, configs/opencv-ovms/models/2022/update_server_device.py, docker-run-opencv-ovms.sh
Adding python script to update the config file based on an environment variable the user can pass in. This will be required for automated testing and benchmarking.
close: #63
build ovms containers as normal
Run docker run with the DEVICE environment variable set to something other than CPU
PIPELINE_PROFILE="grpc_python" DEVICE="AUTO" sudo -E ./docker-run.sh --workload opencv-ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0
Check config.json was updated and that the model_server logs show the new target device when loading the models
=> feat: Python script to modify the model device on run time

.github/workflows/scorecard.yml, README.md
=> feat: Add repo action badges

Makefile, docs_src/OVMS/pipelinerun.md
add make clean up segmentation docker container for ovms-client clean up
Fixes: #215
close: #**215**
=> fix: add missing clean up for instance segmentation docker container

docs_src/OVMS/pipelinerun.md, docs_src/pipelinebenchmarking.md, docs_src/pipelinerun.md, docs_src/run_camera_simulator.md
Closes: #218
update documents for OVMS change and benchmarking
close: #218
=> docs: update doc for OVMS change and benchmarking

configs/opencv-ovms/instance_segmentation_demo/python/instance_segmentation_demo.py, configs/opencv-ovms/scripts/run_instance_segmentation.sh
- [x ] Commit Message meets guidelines as indicated in the URL https://github.com/edgexfoundry/edgex-go/blob/main/.github/Contributing.md
Added performance metrics to instance segmentation
0. Rebuild instance segmentation image: **make build-python-apps**
1. Start camera simulator
2. Run pipeline: **PIPELINE_PROFILE="instance_segmentation" RENDER_MODE=1 sudo -E ./docker-run.sh --workload opencv-ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0**
3. Observe files under results folder. It can take 1 min to show the content.
=> feat: added performance output files to instance segmentation app

Makefile
Closes: #217
makefile
close: #217 
make list-profiles
you should see list of profiles we have and example how to apply it to pipeline run script command
=> feat: create a make target to list all ovms pipeline profiles

get-options.sh
Closes: #227
add new env variables into get-options.sh
close: #227 
./get-options.sh
=> fix: add new env variables into get-option.sh

benchmark-scripts/collect_platform_metrics.sh
=> fix: resolve the issues for pcm-memory in the container

.github/workflows/gh-pages.yml
- [ x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
=> docs: Added github pages to automate deployment of github pages

configs/opencv-ovms/demos/instance_segmentation/python/instance_segmentation_demo.py, configs/opencv-ovms/demos/object_detection/python/object_detection_demo.py, configs/opencv-ovms/scripts/run_instance_segmentation.sh, configs/opencv-ovms/scripts/run_object_detection.sh
Quick fix to make mqtt argument optional.
=> fix: mqtt argument

docs_src/OVMS/supportingDifferentModel.md, download_models/Dockerfile.downloadModels, download_models/Makefile, download_models/downloadModelsFromList.sh, download_models/downloadOVMSModels.sh, download_models/models.lst
feat: download all models from list and convert them to IR
Closes: #242
adding dockerfile, makefile, script to download rest of ovms models and convert them to IR; all files created are under download_models directory
close: #242 
cd download_models
make build
make run
you should see output models downloaded in configs/opencv-ovms/models/2022/modelslist/
download_models/models.lst has the full models list to download, it could take long time and big memory usage if you download it all, you can delete or comment out some to make smaller list for fast testing.
=> feat: download all models from list and convert them to IR

.gitignore, configs/opencv-ovms/cmd_client/res/grpc_python/configuration.yaml, configs/opencv-ovms/demos/common/python/openvino/model_zoo/model_api/adapters/ovms_adapter.py, configs/opencv-ovms/models/2022/config.json, configs/opencv-ovms/models/2022/config_template.json, configs/opencv-ovms/scripts/grpc_python.py, configs/opencv-ovms/scripts/grpc_python_test.py, configs/opencv-ovms/scripts/run_grpc_kserv.sh, configs/opencv-ovms/scripts/run_instance_segmentation.sh, configs/opencv-ovms/scripts/run_object_detection.sh, docs_src/OVMS/pipelinerun.md, docs_src/OVMS/supportingDifferentModel.md, download_models/downloadOVMSModels.sh, download_models/testDownloadOVMSModels.sh
- [ x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
Delete person vehicle bike model folder
Re-download models, and run pipelines.
=> fix: Fixed regex to accept hyphen (-) on ovms model name

docker-run-opencv-ovms.sh, get-options.sh
Make sure you have all docker images built, models, and simulators running.
use **--platform dgpu.0** and **DEVICE=GPU** to run inferencing on GPU
_PIPELINE_PROFILE="object_detection" RENDER_MODE=1 DEVICE=GPU sudo -E ./docker-run.sh --workload opencv-ovms --platform dgpu.0 --inputsrc rtsp://127.0.0.1:8554/camera_1_
=> fix: mounting gpu device properly without privileged mode

docker-run-opencv-ovms.sh, docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md, download_models/downloadModelsFromList.sh, download_models/downloadOVMSModels.sh
generic pipeline: add docs for user to add new models to run object detection, update model downloading using existing openvino model zoo model downloader ubuntu20_dev
PIPELINE_PROFILE="object_detection" RENDER_MODE=0 MQTT=127.0.0.1 sudo -E ./benchmark.sh --pipelines 1 --logdir mytest/data --duration 120 --init_duration 120 --platform core --inputsrc rtsp://127.0.0.1:8554/camera_3 --workload opencv-ovms
above command will trigger benchmark run 1 pipeline which will trigger to download new  model, at the end, you should see new model (person-vehicle-bike-detection-2000) been downloaded
=> feat: generic pipeline configuration

docs/404.html, docs/OVMS/pipelinerun.html, docs/OVMS/pipelinesetup.html, docs/OVMS/runObjectDetectionPipelineWithNewModel.html, docs/OVMS/supportingDifferentLanguage.html, docs/OVMS/supportingDifferentModel.html, docs/camera_serial_number.html, docs/environment_variables.html, docs/faq.html, docs/hardwaresetup.html, docs/index.html, docs/pipelinebenchmarking.html, docs/pipelinerun.html, docs/pipelinesetup.html, docs/platforms.html, docs/query_usb_camera.html, docs/references.html, docs/release-notes/v1-0-1.html, docs/release-notes/v1-5-0.html, docs/releasenotes.html, docs/roadmap.html, docs/run_camera_simulator.html, docs/telemetry/setup.html, docs_src/environment_variables.md
Fixes: #260
The real fix is on this documentation source md file: **docs_src/environment_variables.md**  
others are by-products of generated docs from `make build-docs` 
close: #**260**
- run `make build-docs`
- to verify, cd to the directory of containing environment variables docs: `cd docs`
- copy the result of `pwd` command from the console: `pwd`
- open your browser and open this file locally: on the browser address bar put the file protocol and the result of `pwd` with the environment_variables.html file name. so something like this: `file:///home/jimwang/go/src/github.com/intel-retail/automated-self-checkout/vision-self-checkout/docs/environment_variables.html` and you should be able to see now the formatting issue is fixed in the browser html page.
=> docs: fix the env documentation formatting issue

docker-run-opencv-ovms.sh
Removing gst strings from the USB inputsrc. 
close: #266 
1. Build OVMS client and server
2. Connect a USB camera to your system
3. test with docker run RENDER_MODE with a USB camera 
-  PIPELINE_PROFILE="instance_segmentation" RENDER_MODE="1" sudo -E ./docker-run.sh --platform core --inputsrc /dev/video4 --workload opencv-ovms
=> fix: Remove gst inputsrc string addition for USB cameras

Makefile, run-ovms.sh
- [ x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
=> fix: upgraded to openvino 2023.1

Makefile, benchmark-scripts/stream_density.sh, configs/opencv-ovms/cmd_client/main.go, configs/opencv-ovms/cmd_client/res/grpc_go/configuration.yaml, configs/opencv-ovms/grpc_go/.dockerignore, configs/opencv-ovms/grpc_go/Makefile, configs/opencv-ovms/grpc_go/README.md, configs/opencv-ovms/grpc_go/stream_density_run.sh, configs/opencv-ovms/scripts/run_grpc_go.sh, configs/opencv-ovms/scripts/run_object_detection.sh
- make build-grpc-go
- for **run.sh** test:
```console
$ ./camera-simulator/camera-simulator
$ PIPELINE_PROFILE="grpc_go" sudo -E ./run.sh --workload ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0
```
you should see the profile-launcher kicks off the grpc_go profile and runs.
I added `make profile-launcher-status` command to check the current status of profile-launcher.
This profile will run some time, and you can use `make clean-profile-launcher` to stop it any time.
Then you can check the r0.jsonl file to see the outputs.
- for **stream-density** test:
```console
$ cd ./benchmark-scripts
$ PIPELINE_PROFILE="grpc_go" sudo -E ./benchmark.sh --stream_density 15.0 --logdir grpc_go/data --duration 120 --init_duration 40 --workload …
```
=> feat: refactor grpc_go and object_detection profile to use the current profile-launcher

configs/opencv-ovms/models/2022/config_template.json, download_models/downloadOVMSModels.sh
add ability to download public models like efficientnet
run the script `./download_models/downloadOVMSModels.sh`
=> feat: Download public models like the efficientnet classification model

Makefile, configs/opencv-ovms/scripts/run_gst.sh
FIXES: #226
close: #**226**
- make build-profile-launcher
- run camera-simulator: `$ ./camera-simulator/camera-simulator.sh`
- run gst profile: 
```console
$  PIPELINE_PROFILE="gst" RENDER_MODE=0 sudo -E ./run.sh --workload ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 
```
observe that now the pipeline is running ok and outputs fps in `pipeline0.log` file under ./results/ folder.
- You can also test the stream-density for gst profile now too: 
```console
$ cd ./benchmark-scripts
$ PIPELINE_PROFILE="gst" RENDER_MODE=0 sudo -E ./benchmark.sh --stream_density 14.95  --logdir gst/data --duration 120 --init_duration 40 --workload ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0
```
=> fix: resolve the gst profile running issue from profile-launcher

configs/opencv-ovms/demos/classification/python/classification_demo.py, configs/opencv-ovms/demos/common/python/images_capture.py, configs/opencv-ovms/demos/instance_segmentation/python/instance_segmentation_demo.py, configs/opencv-ovms/demos/object_detection/python/object_detection_demo.py
1. Rebuild python apps: make build-python-apps
2. Run camera simulator
3. Run instance seg pipeline: PIPELINE_PROFILE="instance_segmentation" RENDER_MODE=1 sudo -E ./run.sh --workload ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0
Instance segmentation pipeline doesn't exit after few minutes.
=> fix: fix instance segmentation exiting due to decode issue

Makefile, configs/opencv-ovms/cmd_client/Dockerfile, configs/opencv-ovms/cmd_client/Makefile
Building process of profile-launcher
close: #293
1. make build-profile-launcher
=> feat: Use docker to build profile-launcher

.gitignore, Makefile, configs/opencv-ovms/cmd_client/main.go, configs/opencv-ovms/cmd_client/readEnv.go, configs/opencv-ovms/cmd_client/readEnv_test.go, configs/opencv-ovms/cmd_client/res/classification/configuration.yaml, configs/opencv-ovms/cmd_client/res/grpc_go/configuration.yaml, configs/opencv-ovms/cmd_client/res/grpc_python/configuration.yaml, configs/opencv-ovms/cmd_client/res/gst/configuration.yaml, configs/opencv-ovms/cmd_client/res/instance_segmentation/configuration.yaml, configs/opencv-ovms/cmd_client/res/object_detection/configuration.yaml, configs/opencv-ovms/cmd_client/res/test/configuration.yaml, configs/opencv-ovms/envs/ovms_server.env, configs/opencv-ovms/scripts/start_ovms_server.sh, run-ovms.sh, run_smoke_test.sh
- make build-profile-launcher
- start camera-simulator: `./camera-simulator/camera-simulator.sh`
- for "test" profile:
```console
PIPELINE_PROFILE="test" sudo -E ./run.sh --workload ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0
```
- for "classification" profile:
```console
PIPELINE_PROFILE="classification" RENDER_MODE=1 sudo -E ./run.sh --workload ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0
```
- you can also run `smoke tests` from make file target: 
```console
make run-smoke-tests
```
it will take a while but it should show ALL PASSED for all ovms profiles.
=> feat: implementation of single container / client-server through profile-launcher

benchmark-scripts/format_avc_mp4.sh
close: #303
1. cd benchmark-scripts
2. ./download_sample_videos.sh
=> refact: changed docker image to convert sample videos

README.md
- [x ] Updated Documentation as relevant to the changes
=> docs: Updating README for a QuickStart

docs_src/OVMS/pipelinerun.md, docs_src/OVMS/pipelinesetup.md, docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md, docs_src/OVMS/supportingDifferentLanguage.md, docs_src/OVMS/supportingDifferentModel.md, docs_src/camera_serial_number.md, docs_src/hardwaresetup.md, docs_src/pipelinebenchmarking.md, docs_src/pipelinerun.md, docs_src/pipelinesetup.md, docs_src/query_usb_camera.md, docs_src/run_camera_simulator.md, docs_src/webcam_rtsp.md, mkdocs.yml
- Update documentation to use `!!! Note` format - also split out Example, Success, Failure where I found them
- Added a footer to help with navigation
Run `make serve-docs`
Ensure that all the notes are formatted properly.
=> docs: Update note format to use pymdownx.details, add footer

docs_src/OVMS/pipelinesetup.md, docs_src/OVMS/profileLauncherConfigs.md
=> docs: add documentation for profile launcher configuration

configs/opencv-ovms/envs/capi_face_detection.env, docs_src/OVMS/capiPipelineRun.md, mkdocs.yml
add gst capi face detection documentation
=> docs: add gst capi face detection documentation

.gitignore, configs/opencv-ovms/demos/object_detection/python/labels/person_vehicle_bike_detection_2000.txt, configs/opencv-ovms/models/2022/config_template.json, docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
update object detection model and docs
close: #325 
1. start camera simulator
2. run PIPELINE_PROFILE="object_detection" RENDER_MODE=1 sudo -E ./run.sh --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload ovms
=> feat: update object detection model and docs

Makefile, docs_src/camera_serial_number.md, get-realsense-serialno.sh
close: #**306**
- plug in your realsense camera into system
- run build: `make build-dlstreamer-realsense`
- run get serial number makefile target: `make get-realsense-serial-num`
=> feat: enhance getting realsense camera serial number into a script and makefile target

download_models/downloadOVMSModels.sh
Closes: #326
download ovms models to requested precision only
close: #326 
1. delete previously downloaded models folder under configs/opencv-ovms/models/2022
2. cd download_models
3. ./downloadOVMSModels.sh
after step 3, you should observe models been downloaded and only the requested precision folder been created download each model folder
=> feat: download ovms models to requested precision only

configs/opencv-ovms/demos/instance_segmentation/python/instance_segmentation_demo.py, configs/opencv-ovms/scripts/docker-launcher.sh
- [ x] Commit Message meets guidelines as indicated in the URL https://github.com/intel-retail/automated-self-checkout/blob/main/CONTRIBUTING.md
**CONTAINER_NAME** env variable is needed as a MQTT topic name for the python apps.
close: #321
=> fix: missing containername env variable

docs_src/LICENSE.md, docs_src/OVMS/pipelinesetup.md, docs_src/hardwaresetup.md, docs_src/index.md, docs_src/pipelinebenchmarking.md, docs_src/pipelinesetup.md, docs_src/query_usb_camera.md
Change the numbering to 1., 2., 3. and add the License
> Note: This will not address formatting yet. That will be covered in a later PR.
=> refactor: Rework numbering in docs and add License

docs_src/OVMS/pipelinerun.md, docs_src/OVMS/quick_pipelinerun.md, docs_src/faq.md, docs_src/hardwaresetup.md, docs_src/pipelinebenchmarking.md, docs_src/pipelinerun.md, docs_src/pipelinesetup.md, docs_src/pipelinesetup_dlstreamer.md, docs_src/release-notes/v1-0-1.md, docs_src/run_camera_simulator.md, mkdocs.yml
restructure docs - this just lumps everything under Getting Started.
=> refactor: Restructure docs for better flow

Makefile, docs_src/OVMS/quick_stream_density.md, mkdocs.yml
- `make build-docs`
- open the html file in browser to see the documentation: file:///&lt;file_path_to_quick_stream_density.html&gt;
=> docs: add quick start guide documentation for stream density

run-ovms.sh
- make clean-all
- make build-profile-launcher
- make run-camera-simulator
- first run gst profile with camera-simulator: `PIPELINE_PROFILE=gst sudo -E ./run.sh --workload ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0`
-  check the docker ps -a and docker logs of the first instance of gst docker container: it should run as normal and outputs fps
- then we run gst profile with your RealSense camera: `PIPELINE_PROFILE=gst sudo -E ./run.sh --workload ovms --platform core --inputsrc your_RealSense_camera_Serial_Number`  ;   to get your RealSense camera serial number you can run script `./get-realsense-serialno.sh` or run makefile target: `make get-realsense-serial-num`  
- check the docker ps -a and docker logs of the **second** …
=> Adjust gst profile DockerImage accordingly with the input source if RealSense or not

docs_src/telemetry/setup.md, telegraf/Dockerfile, telegraf/docker-run-telegraf.sh, telegraf/opt/intel-gpu-telegraf/get_intel_gpu_status.sh
Follow the instructions here: https://intel-retail.github.io/automated-self-checkout/telemetry/setup.html
Do not use the word password as password since it is blacklisted by influxdb.
=> fix: telegraf image was not working properly

get-realsense-serialno.sh, run_smoke_test.sh
smoke test for gst profile using RealSense camera if found
Closes: #339
close: #**339**
- plug in the RealSense camera into the system if not yet
- run smoke tests: `make run-smoke-tests`   and you should see ALL PASSED including the one with RealSense camera as the input source.
=> feat: add smoke test for running gst profile with RealSense camera if found

.gitignore, docs_src/OVMS/pipelinerun.md, docs_src/environment_variables.md, docs_src/hardwaresetup.md, docs_src/index.md, docs_src/pipelinesetup.md, docs_src/run_camera_simulator.md, docs_src/telemetry/setup.md, mkdocs.yml
build docs using `make serve-docs`
=> docs: Reorganize docs to create less tabs across the top

configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
=> feat: add text output to capi yolov5 object detected

docs_src/OVMS/pipelinesetup.md
=> docs: fix make build-ovms-server documentation

configs/opencv-ovms/cmd_client/main.go, configs/opencv-ovms/cmd_client/res/capi_face_detection/configuration.yaml, configs/opencv-ovms/gst_capi/Dockerfile.ovms-capi-gst, configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp, configs/opencv-ovms/gst_capi/pipelines/face_detection/main.cpp
Fixes: #378
close: #**378**
- make build-capi_face_detection
- make build-capi_yolov5
- go to ./configs/opencv-ovms/models/2022 folder and delete config.json file if exists
- make run-camera-simulator
- run C-API pipelines: for example capi_yolov5 `PIPELINE_PROFILE="capi_yolov5" RENDER_MODE=1 sudo -E ./run.sh --workload ovms --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 `    verify that it is working for object detection yolov5; and you can also test it capi_face_detection profile
- run unit-test-profile-launcher  all PASSED
- run smoke-tests all PASSED
=> fix: resolve the issue of missing config.json for C-API cases

configs/opencv-ovms/gst_capi/pipelines/capi_yolov5/main.cpp
PIPELINE_PROFILE="capi_yolov5" RENDER_MODE=1 sudo -E ./run.sh --platform core --inputsrc rtsp://127.0.0.1:8554/camera_0 --workload ovms
you should see object detected with bounding boxes around them.
=> feat: enhanced capi yolov5 bounding boxes

docs_src/OVMS/capiYolov5EnsemblePipelineRun.md
=> docs: Adding Barcode env var documentation

benchmark-scripts/Dockerfile.xpu
Updating XPU manager as a result of the previous version being removed from github
close: #394 
1. cd benchmark-scripts
2. make build-xpu or make build-all
3. See failure
=> fix: Update xpu manager release

Makefile, configs/opencv-ovms/gst_capi/Dockerfile.ovms-capi-gst, configs/opencv-ovms/gst_capi/Makefile
=> feat: Capi improvement to choose dGPU to build

benchmark-scripts/benchmark.sh, benchmark-scripts/test_benchmark_multiple_pipelines.sh
Fixes: #401
close: #**401**
- change directory to ./**benchmark-scripts**
- run tests with test script: `./test_benchmark_multiple_pipelines.sh`  and you should see all PASSED at the end (it will run much longer if this is the first time since it takes time to build capi_yolov5)
- run smoke tests should see all PASSED: `cd ..;  make run-smoke-tests`
-
=> fix: resolve the bug of benchmark script when run multiple pipelines with --pipelines 2 or more

docs_src/faq.md
- Add pipeline container logs info in FAQ
`make serve-docs`
=> docs: faq changes

docs_src/OVMS/pipelinerun.md
Fix the issue in this page: https://intel-retail.github.io/automated-self-checkout/OVMS/pipelinerun.html
=> docs: fix the missing pipeline profile in the input src table example

docs_src/OVMS/pipelinesetup.md
Fix the issue in this page: https://intel-retail.github.io/automated-self-checkout/OVMS/pipelinesetup.html
=> docs: fix the formatting issue for pipeline setup docs page

docs_src/OVMS/pipelinebenchmarking.md
Fix the issue in this page: https://intel-retail.github.io/automated-self-checkout/OVMS/pipelinebenchmarking.html
=> docs: fix the formatting issue of pipeline benchmarking docs page

telegraf/Dockerfile
=> fix: XPU Manager version update in the telegraf Dockerfile

.github/workflows/integration.yaml
=> feat: Add integration workflow for runner

.github/workflows/integration.yaml
=> Integration

.github/workflows/integration.yaml
=> fix: Update integration.yaml

.github/workflows/integration.yaml
=> fix: Run on runner instead of default ubuntu

.github/workflows/integration.yaml
=> fix: Use labels for runner

configs/opencv-ovms/demos/classification/python/entrypoint.sh, configs/opencv-ovms/demos/instance_segmentation/python/entrypoint.sh, configs/opencv-ovms/demos/object_detection/python/entrypoint.sh, configs/opencv-ovms/grpc_go/entrypoint.sh, docs_src/hardwaresetup.md
- Add Docker version in documentation
- echo results dir in the docker container before starting pipeline
- Check update in documentation
- Check pipeline containers for the message
=> feat: update docker version + container logs

Makefile, configs/opencv-ovms/cmd_client/main.go, configs/opencv-ovms/models/2022/config_template.json, configs/opencv-ovms/scripts/gen_ovms_model_config_json.sh, docker-compose.yml
closes: #434
add the generating config.json file before running docker compose up to fix the problem.
close: #434 
make run-pipelines
make down-pipelines
make run-smoke-tests
=> fix: docker compose up failed with "Error: configuration file not found or cannot open"

Makefile
make run-cached-demo only works when you have run-demo before.
=> feat: add run cached demo

Makefile
closes: #437
Makefile to add checking to delete config.json only if it exists
close: #437 
run command `make clean-all` before running `make run-pipelines`, with this PR, you will not see error anymore
=> fix: make clean-all has error if the first time or without running docker-compose

run_smoke_test.sh
Add gst with classification into smoke tests
- run smoke tests: `make run-smoke-tests`
- should see ALL PASSED
=> feat: add gst classification smoke test

benchmark-scripts/requirements-xpu.txt
FIXES: #444
close: #**444**
The latest version of grpcio is 1.60.0: https://github.com/grpc/grpc/releases   not 1.60.2
- docker rmi benchmark:xpu
- ( cd ./benchmark-scripts; make )
- should see all builds successfully
=> fix: update the xpu requirement.txt for benchmark docker image built

mkdocs.yml
Closes: #447
close: #447 
1. run `make serve-docs`
2. when a page loads ensure that sections in the LH nav get highlighted and added to the link (even for nested sections)
=> docs: Add anchoring for navigation and toc

docs_src/OVMS/quick_stream_density.md, docs_src/troubleshooting.md
=> docs: add documentation for changing model precision while running on device GPU

run_smoke_test.sh
- run `make run-smoke-tests` and should see ALL PASSED
=> feat: add smoke tests for running on device GPU

docs_src/hardwaresetup.md, docs_src/pipelinesetup.md, mkdocs.yml
=> docs: Remove choose pipeline page

docs_src/OVMS/pipelinerun.md, docs_src/OVMS/stop_pipeline_run.md, docs_src/OVMS/supportingDifferentLanguage.md, docs_src/OVMS/supportingDifferentModel.md, docs_src/dev-tools/run_camera_simulator.md, mkdocs.yml
docs updates
run `make serve-docs` and ensure tables and nav works.
=> docs: Re-organize OVMS Run Pipeline section

docs_src/dev-tools/environment_variables.md
run `make serve-docs` and check the environment variable page
=> docs: clean up environment variables page to remove DLStreamer refs

mkdocs.yml
=> docs: Add code copy buttons

docs_src/dev-tools/environment_variables.md
=> fix: Restore GST env vars

docs_src/troubleshooting.md
=> docs: fix the formatting json issue of troubleshooting page

docs_src/OVMS/camera_serial_number.md, docs_src/OVMS/capiPipelineRun.md, docs_src/OVMS/pipelineDockerCompose.md, docs_src/OVMS/pipelinebenchmarking.md, docs_src/OVMS/runObjectDetectionPipelineWithNewModel.md
=> docs: Fix code comment blocks to make it easier to read

run_smoke_test.sh
=> fix: use GPU on DEVICE env to test on serpent canyon

docs_src/OVMS/pipelinebenchmarking.md, docs_src/OVMS/quick_stream_density.md, docs_src/dev-tools/overview.md
run `make serve-docs` and ensure pages render properly
=> docs: Update formatting, ensure pages render properly

benchmark-scripts/collect_platform_metrics.sh, docs_src/OVMS/pipelinebenchmarking.md, docs_src/OVMS/quick_stream_density.md, docs_src/dev-tools/environment_variables.md
=> fix: swaping igt filename to align with GPU.0 or GPU.1

benchmark-scripts/requirements-xpu.txt, benchmark-scripts/requirements.txt, requirements.txt
dependabot updates
close: #440 
close: #458 
close: #459 
close: #471 
close: #472 
- make run-smoke-tests
=> fix: dependabot updates

benchmark-scripts/download_sample_videos.sh, benchmark-scripts/format_avc_mp4.sh, docs_src/dev-tools/run_camera_simulator.md
Closes: #451
close: #451
1. Delete downloaded videos in the `sample-media` folder.
2. change to the benchmark script dir `cd benchmark-scripts`
3. download the sample videos (either with or without the width, height, and fps `./download_sample_videos.sh`
4. run the camera simulator
5. ensure that the indexes of the simulated cameras match the docs
6. run tests/pipelines/benchmarking as desired.
=> feat: Add indexing to camera simulator videos

docker-compose-cam.yml, docker-compose.yml
updated camera sim file names
1. download videos - `cd benchmark-scripts; ./download_sample_videos.sh 3840`
2. run the docker compose pipelines: `make run-pipelines`
3. verify that the camera simulators are up and running
4. tear down - `make down-pipelines`
=> fix: Add indexes to docker compose for camera simulators

docs_src/dev-tools/documentation.md
=> doc: update on mike tool

mkdocs.yml
close: #**490**
1) push a new version `mike deploy 1.0` 
2) run `mike serve` (if error, then upgrade mkdocs-material to latest version)
3) view doc at `http://localhost:8000/1.0
4) Verify if code block (bash/json) is broken on pages -  dev-tools/documentation.html or troubleshooting.html
=> fix: docs versioning bug

docs_src/hardwaresetup.md, docs_src/troubleshooting.md
Closes: #366
close: #366, #367
check the hardware page, troubleshooting page
=> docs: Update arc instructions, add troubleshooting

configs/opencv-ovms/cmd_client/go.mod
…lities
Dependency update based on dependabot vulnerability scan
- make build-profile-launcher
or
- make run-demo
=> fix: update go.mod net version to fix several high security vulnerability

docs_src/release-notes/v2-1-0.md
=> doc: Release notes for 2.1

.github/workflows/scorecard.yml
Adding default github token to the scorecard action.
close: #529
=> fix: OSSF scorecard token

.github/workflows/scorecard.yml
Updating scorecard to version 2.3.1 to fix the invalid token issue.
Github actions are transitioning from Node 1.6 to Node 2.0 which will require some actions to be updated to function properly.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
close: #529
=> Fix: Scorecard version update to 2.3.1

README.md
=> fix: Update discord link

Makefile, README.md, smoke_test.sh
=> feat: Add smoke test for new pipeline docker compose

README.md
Update the discord link to never expire.
=> fix: Update discord links

README.md
=> doc: fix documentation link and update performance tools hash

src/docker-compose.yml
Remove the build process from the docker compose file.
close: #568 
1. make run-demo
2. notice that the camera-simulator0 build is no longer there and a docker pull image is only used
3. see demo is running
=> fix: Remove unused build step from camera simulator

src/docker-compose.yml
Docker port needs to be linked to localhost since the other containers are using host network. This will possibly change in the future but for now works.
- download PR
- make run-demo
- Should see demo window appear with video and object detection
=> fix: Revert network back to localhost

helm/Dockerfile.cam-sim, src/docker-compose.yml, src/pipeline-server/docker-compose.pipeline-server.yml
Pexels changed their URL format for downloads so new URls are required.
make run-demo
=> fix: update pexels link with new URL path

src/pipeline-server/requirements.txt, src/requirements.txt
- Updates Opencv-python package requirements 
close: #596 
- Run `make run-demo` from clean docker environment and observe success
=> fix: dependabot update opencv-python

helm/Dockerfile, src/Dockerfile
- Updates dlstreamer image to use 2024.1.1-dev
- Cleans up a warning about casing of `as` in Dockerfile
- Run `make run-demo`
https://github.com/intel-retail/performance-tools/pull/58
=> feat: update dlstreamer to use 2024.1 image

helm/Dockerfile, src/Dockerfile
=> fix: revert as casing in dockerfile to resolve codeql vuln

src/pipeline-server/docker-compose.pipeline-server.yml
Reverting pipeline images to the 2.0 version
=> fix: Revert the servers to the proper image

.github/workflows/build.yaml, .github/workflows/codeql.yaml, .github/workflows/gotest.yaml, .github/workflows/integration.yaml, .github/workflows/reports.yaml, .github/workflows/reviewdog.yaml, .github/workflows/scorecard.yml, .github/workflows/trivy-scan.yaml, .github/workflows/trivyimagescan.yaml
- Updated the GitHub Actions jobs to improve scanning and building images jobs
=> feat: update GitHub actions jobs

.github/release.yml
=> fix: change issue label -> bug

src/pipeline-server/docker-compose.pipeline-server.yml
Some grafana ENV are required for the dashboard to properly launch.
1. make build-pipeline-server
2. make run-pipeline-server
3.
=> fix: Add missing grafana ENV

.github/.reviewdogConfig.yml, .github/workflows/reviewdog.yaml
We are changing pep8 to pycodestyle , this fixes the reviewdog github action works properly.
close: #**647**
=> fix: Change pep8 to pycodestyle for fixing failure due to reviewdog GitHub action

src/entrypoint.sh
=> fix :RTSP stream | added sleep of 5 secs | Resolves: #633

.github/workflows/reviewdog.yaml, src/common-service/Dockerfile, src/common-service/requirements.txt, src/retail-data-visualization/Dockerfile.grafana, src/retail-data-visualization/Dockerfile.retail-data-visualization
- `make run-demo` works
- grafana dashboard under src/retail-data-visualization works. Instructions to run are here - https://github.com/intel-retail/automated-self-checkout/tree/main/src/retail-data-visualization
=> fix: scorecard issues for sdle

src/benchmark-commands.md, src/docker-compose.yml, src/pipelines/yolov5s_effnetb0.sh
Set batch size using BATCH_SIZE environment variable instead of hardcoding. Also fix benchmark example typo.
close: #672
=> refactor: set batch size from env variable

src/res/yolov5-gpu.env
Add file yolov5-gpu.env
close: #660
Run `make run-smoke-tests`
=> bug: add file yolov5-gpu.env

Makefile, src/pipeline-server/Dockerfile.pipeline-server, src/pipeline-server/docker-compose.pipeline-server.yml
Update docker image tag for intel/edge_video_analytics_microservice to 2.2.0
close: #683
=> bug: fix github actions build-pipeline-server failure

src/pipelines/yolov5s.sh, src/pipelines/yolov5s_effnetb0.sh, src/res/all-cpu.env, src/res/all-dgpu.env, src/res/all-gpu.env, src/res/all-npu.env, src/res/yolov5-cpu-class-gpu.env, src/res/yolov5-gpu-class-cpu.env, src/res/yolov5-gpu.env
Optimized pipelines
PIPELINE_SCRIPT=yolov5s_effnetb0.sh DEVICE_ENV=res/all-gpu.env make run-demo
=> fix: update deprecated syntax in dlstreamer commands

.github/workflows/codeql.yaml, .github/workflows/reviewdog.yaml, .github/workflows/scorecard.yml, .github/workflows/trivy-scan.yaml, .github/workflows/trivyimagescan.yaml
=> fix: update github actions

Makefile
=> refact: Add consolidate metrics Make target

Makefile, src/Dockerfile
- Implemented a regex-based check in the run-render-mode Makefile target to accept only local X11 DISPLAY values like :0 or :0.0, while rejecting remote/forwarded ones.
close: #**[issue_number](https://github.com/intel-retail/automated-self-checkout/issues/738)**
=>  Improved DISPLAY Validation Regex in Makefile

download_models/downloadAndQuantizeModel.sh
=> quantize yoloFP16 to INT8

download_models/Dockerfile, download_models/efnetv2b0_download_quantize.py, src/docker-compose.yml, src/pipelines/yolo11n.sh, src/pipelines/yolo11n_effnetv2b0.sh, src/pipelines/yolo11n_full.sh
=> LP: changes Not download model effnet model if exist and added restart on failure in dc and set -eo pipefail

README.md, benchmark-commands.md
=> Doc updates

src/Dockerfile
=> Update DLS release image

download_models/Dockerfile, download_models/download_age_prediction.sh, download_models/download_effnetb0.sh, src/pipelines/obj_detection_age_prediction.sh, src/pipelines/yolo11n_effnetb0.sh
1. Commented out Effnet V2B0 download script.
2. Added imagenet file and model-proc file for effnet B0 independently.
3. Set proxy variables in download_effnetb0.sh and download_age_prediction.sh
=> Resolved the proxy issue and commented out the EfficientNet V2B0 model.

Makefile, helm/Dockerfile, helm/values.yaml
=> Removed hardcoded proxy values
